### ISSUE TITLE
TBSignatureProfiler with microarray data?

### ISSUE THREAD

**Issue by BirongZhang** [wejlab/TBSignatureProfiler#31]
Hi Brie,

I hop you are doing great!

A quick question: can I use **TBSignatureProfiler with normalised microarray data**?
<img width="334" alt="Screenshot 2024-03-08 at 10 28 06" src="https://github.com/wejlab/TBSignatureProfiler/assets/74430395/8e29cefc-e376-422f-ad03-bb965a0930c8">

Looking forward to hearing you. Thanks.

Kind regards,
Birong

**Comment by BirongZhang** [comment]
Hi Brie,

Here is my scripts, it worked great last year:
```
out <- capture.output(ssgsea_result <- runTBsigProfiler(input = BRCA,
                                                        useAssay = "log_counts",
                                                        signatures = Signature ,
                                                        algorithm = "ssGSEA",
                                                        combineSigAndAlgorithm = TRUE,
                                                        parallel.sz = 1,
                                                        update_genes = FALSE))
```

But this year, I got the following error:
```
Running ssGSEA
Error: useNames = NA is defunct. Instead, specify either useNames = TRUE or useNames = FALSE.
```
Then I reinstalled  the package, got this new error:
```
Running GSVA
Error: 'gsvaParam' is not an exported object from 'namespace:GSVA'
```

Could you please have a look at this? Thanks.

Kind regards,
Birong

**Comment by aubreyodom** [comment]
Hi Birong,

That's a known bug from a package dependency that is currently only fixed in the most recent version of the GSVA package. Can you update that package to the Bioconductor version and see if it works? Also make sure to use the Github version of the TBSP.
```
if (!requireNamespace("devtools", quietly = TRUE))
  install.packages("devtools")
devtools::install_github("wejlab/TBSignatureProfiler")

BiocManager::install("GSVA")
```
Thanks,
Brie

**Comment by BirongZhang** [comment]
Hi Brie,

Thanks for your kind help.
Sorry for mu stupid question. I re-installed GSVA, the "error: 'gsvaParam' is not an exported object from 'namespace:GSVA'" has been solved.

But I got another error:
```
Running ssGSEA
Error in (function (cond)  : error in evaluating the argument 'x' in selecting a method for function 't': useNames = NA is defunct. Instead, specify either useNames = TRUE or useNames = FALSE.
```

Any advice would be highly appreciated. Thanks!

Kind regards,
Birong

**Comment by BirongZhang** [comment]
Hi Brie,

Never mind.

I installed the R/4.3.3, and updated GSVA, SummarizedExperiment, and TBSignatureProfiler.
Problem solved!

Thanks very much for your time and help!

Best regards,
Birong
